config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'root#index'

  resources :admin, only: [:index]

  namespace :admin do
    resources 'canam' do
      delete :tournament_round_matches
      post :generate_tournament_round_matches
      get :assign_courts # need a param here
      post :process_courts
      collection do
        post :import
        get :player
        get :summary
      end
    end
    resources 'matches'
    resources 'seasons', only: [:show]
    resources 'teams' do
      collection do
        post :import
        post :import_selection
      end
    end
  end

  resources :divisions, only: [:index, :show]
  get '/divisions/:id/playoff', to: 'divisions#show_playoff', as: :division_playoff
  get '/divisions/:id/week/:week', to: 'divisions#week', as: :division_week
  post '/divisions/:id/week/:week/report', to: 'divisions#week_report', as: :division_week_report

  resources :faq, only: [:index]
  get 'bracket/current', to: 'bracket#current', as: :current_bracket
  resources :bracket
  resources :games, only: [:update]
  resources :isa, only: [:index]
  resources :live, only: [:index, :lower_third, :four_frame_summary, :four_game, :full_game, :two_game, :summary]
  get 'live/lower_third', to: 'live#lower_third', as: :lower_third
  get 'live/four_frame_summary', to: 'live#four_frame_summary', as: :four_frame_summary
  get 'live/full_game', to: 'live#full_game', as: :full_game
  get 'live/summary', to: 'live#summary', as: :summary
  get 'live/four_game', to: 'live#four_game', as: :four_game
  get 'live/two_game', to: 'live#two_game', as: :two_game
  get 'live/si/:id', to: 'live#si'
  get 'live/si', to: 'live#si'

  resources :live_events, only: [:update]
  resources :matches
  get 'matches/:id/ae_data', to: 'matches#ae_data', as: :match_ae_data
  resources :privacy, only: [:index]
  resources :root, only: [:index]
  resources :royal_palms_calendar, only: [:index]
  post 'rpc_events', to: 'royal_palms_calendar#index', as: :rpc_events
  resources :seasons, only: [:index, :show]
  get '/seasons/:id/report', to: 'seasons#report', as: :season_report
  resources :teams, only: [:index, :show]
  resources :tournament_rounds, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  require 'elo'

  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  belongs_to :division, optional: true
  belongs_to :court, optional: true
  belongs_to :tournament_round, optional: true # TODO: if exists, ensure unique tournament_order
  has_many :games, -> { order(:number) }, inverse_of: :match, dependent: :nullify

  # TODO: Fix callback to work on updates
  after_create :calculate_elo

  # TODO: home team and away team must be different
  # TODO: if league, validate both teams in same division

  def teams
    [away_team, home_team]
  end

  delegate :season, to: :division

  def winner
    return nil if home_score == away_score

    home_score > away_score ? home_team : away_team
  end

  def calculate_elo
    return unless counts_toward_elo

    throw 'score required for match' unless home_score && away_score

    # TODO: if date < latest match, calculate all of those ELOs as well, as this busts cache

    home_elo = ::Elo::Player.new(rating: home_team.elo_cache, games_played: home_team.match_count)
    away_elo = ::Elo::Player.new(rating: away_team.elo_cache, games_played: away_team.match_count)

    if home_score > away_score
      home_elo.wins_from(away_elo)
    elsif away_score > home_score
      away_elo.wins_from(home_elo)
    end

    # apply the Match's Multiplier to scale the change in elo
    #  expects self::Multiplier to never be nil
    home_elo_change = multiplier * (home_elo.rating - home_team.elo_cache)
    away_elo_change = multiplier * (away_elo.rating - away_team.elo_cache)

    # Save ELO to Match, applying the change in elo
    self.home_old_elo = home_team.elo_cache
    self.away_old_elo = away_team.elo_cache
    self.home_new_elo = home_team.elo_cache + home_elo_change
    self.away_new_elo = away_team.elo_cache + away_elo_change
    save

    # Save ELO to Teams
    unless home_score == away_score
      home_team.update(previous_elo: home_team.elo_cache)
      away_team.update(previous_elo: away_team.elo_cache)
      home_team.update(elo_cache: home_team.elo_cache + home_elo_change)
      away_team.update(elo_cache: away_team.elo_cache + away_elo_change)
    end
  end

  def formatted_date
    return '' unless time

    time.in_time_zone('America/Chicago').strftime("%b #{time.in_time_zone('America/Chicago').day.ordinalize} %Y")
  end

  def formatted_datetime
    return '' unless time

    time.in_time_zone('America/Chicago').strftime("%b #{time.in_time_zone('America/Chicago').day.ordinalize} %Y, %-l:%M%P")
  end

  def formatted_time
    return '' unless time

    time.in_time_zone('America/Chicago').strftime('%-l:%M%P')
  end

  def team_result(id)
    return nil unless [home_team_id, away_team_id].include?(id)

    return 'tied' if home_score == away_score

    return 'won' if home_team_id == id && home_score > away_score
    return 'won' if away_team_id == id && away_score > home_score

    return 'lost' if home_team_id == id && home_score < away_score
    return 'lost' if away_team_id == id && away_score < home_score
  end

  def team_info(id)
    if home_team_id == id
      {
        opponent: away_team,
        result: team_result(id),
        old_elo: home_old_elo,
        new_elo: home_new_elo
      }
    elsif away_team_id == id
      {
        opponent: home_team,
        result: team_result(id),
        old_elo: away_old_elo,
        new_elo: away_new_elo
      }
    end
  end

  def tied?
    home_score == away_score
  end

  def matchup_summary
    away_record = away_team.record
    home_record = home_team.record

    [
      [full_location, away_team.name, home_team.name],
      ['ELO', away_team.elo_cache, home_team.elo_cache],
      ['Record', "#{away_record[:wins]}-#{away_record[:losses]}\t", "#{home_record[:wins]}-#{home_record[:losses]}\t"]
    ]
  end

  def export_summary
    [
      id,
      time.in_time_zone('America/Chicago').iso8601,
      full_location,
      division ? division.name : '',
      comment,
      home_team.name,
      away_team.name,
      winner ? winner.name : '',
      home_score,
      away_score,
      home_old_elo,
      home_new_elo,
      away_old_elo,
      away_new_elo
    ]
  end

  def full_location
    return "#{court.full_name} - #{location}" if court && location
    return court.full_name if court
    return location if location

    ''
  end

  def bracket_meta
    {
      id: id,
      away_team_id: away_team_id,
      home_team_id: home_team_id,
      winning_team_id: winner ? winner.id : nil,
      away_team_name: away_team.display_name,
      home_team_name: home_team.display_name,
      winning_team_name: winner ? winner.display_name : nil,
      time: time # UTC
    }
  end

  def create_palms_doubles_games(first_yellow_team, first_black_team)
    throw 'first_yellow_team must be a Team from this Match' unless [away_team, home_team].include?(first_yellow_team)
    throw 'first_black_team must be a Team from this Match' unless [away_team, home_team].include?(first_black_team)
    throw 'first_yellow_team must not be same as first_black_team' if first_yellow_team == first_black_team

    Game.create(
      match: self,
      number: 1,
      yellow_team: first_yellow_team,
      black_team: first_black_team,
      game_type: 'palms_doubles',
      max_frames: 8,
      allow_ties: false,
      frames: []
    )

    Game.create(
      match: self,
      number: 2,
      yellow_team: first_black_team,
      black_team: first_yellow_team,
      game_type: 'palms_doubles',
      max_frames: 8,
      allow_ties: false,
      frames: []
    )

    Game.create(
      match: self,
      number: 3,
      yellow_team: first_yellow_team,
      black_team: first_black_team,
      game_type: 'palms_doubles',
      max_frames: 4,
      change_colors_every_frames: 2,
      allow_ties: false,
      frames: []
    )
  end

  def ae_data
    {
      starting_yellow_team: games.first.yellow_team.name,
      starting_black_team: games.first.black_team.name,
      yellow_match_score: series_score_progression[0],
      black_match_score: series_score_progression[1],
      frames: games.map(&:frames)
    }
  end

  def self.recalculate_all_elo
    # Disable logging
    old_logger = ActiveRecord::Base.logger
    ActiveRecord::Base.logger.level = 1

    Team.reset_all_elo

    Match.all.order(:time, :id).each(&:calculate_elo)

    # Set logging back to old level
    ActiveRecord::Base.logger = old_logger
  end

  private

  def series_score_progression
    yellow = [0]
    black = [0]

    games.each_with_index do |g, i|
      # when i even (0, 2 / Game 1 & 3), use team series score of your own color
      # when i odd (1 / Game 2), use team series score of your other color
      yellow.push(g.series_score[i % 2])
      black.push(g.series_score[(i + 1) % 2]) # swap that for black scores by increasing i by 1
    end

    [yellow, black]
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < Admin::BaseController
  def index
    # TODO: real order and paginate
    @matches = Match.last(100).reverse
  end

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new
    @court_select = Location.find_by(name: 'Royal Palms Chicago').courts.order(:name).collect { |c| [c.name, c.id] }
    @division_select = Division.all.order('season_id DESC', :day_of_week, :time).collect { |d| [d.la_name, d.id] }
    @team_select = Team.all.order('name').collect { |t| ["#{t.name} (#{t.id})", t.id] }
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to admin_match_path(@match)
    else
      render 'new'
    end
  end

  def edit
    @match = Match.find(params[:id])
    @court_select = Location.find_by(name: 'Royal Palms Chicago').courts.order(:name).collect { |c| [c.name, c.id] }
    @division_select = Division.all.order('season_id DESC', :day_of_week, :time).collect { |d| [d.la_name, d.id] }
    @team_select = Team.all.order('name').collect { |t| ["#{t.name} (#{t.id})", t.id] }
  end

  def update
    @match = Match.find(params[:id])

    if @match.update(match_params)
      redirect_to admin_match_path(@match)
    else
      render 'edit'
    end
  end

  def destroy
    @match = Match.find(params[:id])

    @match.destroy

    redirect_to admin_matches_path
  end

  def match_params
    params.require(:match).permit(
      :time,
      :court_id,
      :division_id,
      :away_team_id,
      :home_team_id,
      :away_score,
      :home_score,
      :multiplier,
      :comment
    )
  end
end

app/controllers/match_controller.rb
class MatchController < ApplicationController
  def new
    @match = Match.new
    @tames = Team.all.order('name')
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to matches_path
    else
      render 'new'
    end
  end

  def index
    @matches = Match.all.order('time DESC')
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @match = Match.find(params[:id])

    # TODO: non-json view as well
    render json: @match, include: [:games]
  end

  def ae_data
    @match = Match.find(params[:id])
    render json: @match.ae_data
  end

  def new
    @match = Match.new
    @tames = Team.all.order('name')
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to matches_path
    else
      render 'new'
    end
  end

  def index
    @matches = Match.all.order('time DESC')
  end
end

app/views/admin/matches/_form.html.erb
<%= form_for [:admin, @match], url: url, method: method do |f| %>
  <div class="form-group">
    <%= f.label 'Time (in UTC):' %>
    <%= f.datetime_select(:time, { minute_step: 15 }) %>
  </div>

  <div class="form-group">
    <%= f.label 'Court:' %>
    <%= f.select(:court_id, @court_select, { include_blank: true }, { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= f.label 'Division:' %>
    <%= f.select(:division_id, @division_select, { include_blank: true }, { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= f.label 'Away Team:' %>
    <%= f.select(:away_team_id, @team_select, {}, { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= f.label 'Home Team:' %>
    <%= f.select(:home_team_id, @team_select, {}, { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= f.label 'Away Score:' %>
    <%= f.text_field :away_score, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'Home Score:' %>
    <%= f.text_field :home_score, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'ELO Multiplier:' %>
    <%= f.text_field :multiplier, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'Comment:' %>
    <%= f.text_field :comment, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/matches/edit.html.erb
<% if @match.errors.any? %>
  <% flash.now[:error] = @match.errors.full_messages %>
<% end %>

<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <%= render partial: 'admin/matches/form', locals: { url: admin_match_path(@match), method: :patch } %>
  </div>
</div>

app/views/admin/matches/index.html.erb
<% provide :title, '[Admin] Matches' %>
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <%= link_to '<i class="fa fa-plus"></i> New Match'.html_safe, new_admin_match_path, class: 'btn btn-primary' %>
    <table class="table">
      <tr>
        <td>id</td>
        <td>Teams</td>
        <td>Time</td>
        <td>Location</td>
        <td></td>
      </tr>

      <% @matches.each do |m| %>
        <tr>
          <td>
            <%= link_to m.id, admin_match_path(m) %>
          </td>
          <td>
            <span class="<%= m.winner == m.away_team ? 'font-weight-bold' : '' %>">
              <%= link_to m.away_team.name, team_path(m.away_team.id) %>
            </span>

            <br>

            <span class="<%= m.winner == m.home_team ? 'font-weight-bold' : '' %>">
              <%= link_to m.home_team.name, team_path(m.home_team.id) %>
            </span>
          </td>
          <td><%= m.formatted_datetime %></td>
          <td><%= m.full_location %></td>
          <td>
            <% if m.comment %>
              <span class="pad" data-toggle="tooltip" data-placement="top" title="<%= m.comment %>">
                <i class="fas fa-exclamation-circle"></i>
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/matches/new.html.erb
<% if @match.errors.any? %>
  <% flash.now[:error] = @match.errors.full_messages %>
<% end %>

<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <%= render partial: 'admin/matches/form', locals: { url: admin_matches_path, method: :post } %>
  </div>
</div>

app/views/admin/matches/show.html.erb
<% provide :title, '[Admin] Matches' %>
<div class="row">
  <div class="col-lg-10 offset-lg-1">

    <%= link_to '<i class="fa fa-edit"></i> Edit Match'.html_safe, edit_admin_match_path(@match), class: 'btn btn-primary' %>
    <%= link_to '<i class="fa fa-trash"></i> Delete Match'.html_safe, admin_match_path(@match), method: :delete, class: 'btn btn-danger' %>

    <table class="table">
      <tr>
        <td>id</td>
        <td colspan=2><%= @match.id %></td>
      </tr>

      <tr>
        <td>Time</td>
        <td colspan=2><%= @match.formatted_datetime %></td>
      </tr>

      <tr>
        <td>Location</td>
        <td colspan=2><%= @match.full_location %></td>
      </tr>

      <tr>
        <td>Division</td>
        <td colspan=2><%= @match.division ? @match.division.name : '' %></td>
      </tr>

      <tr>
        <td>
          Away Team<br>
          Score / ELO Change
        </td>

        <td><%= link_to @match.away_team.name, team_path(@match.away_team.id) %></td>

        <td>
          <%= @match.away_score %>
          <% if @match.winner && @match.winner == @match.away_team %>
            <span class="board-elo-up pad">+<%= @match.away_new_elo - @match.away_old_elo %></span>
          <% elsif @match.winner && @match.winner == @match.home_team %>
            <span class="board-elo-down pad"><%= @match.away_new_elo - @match.away_old_elo %></span>
          <% else %>
            <span class="board-elo-sam pad">0</span>
          <% end %>
        </td>
      </tr>

      <tr>
        <td>
          Home Team<br>
          Score / ELO Change
        </td>

        <td><%= link_to @match.home_team.name, team_path(@match.home_team.id) %></td>

        <td>
          <%= @match.home_score %>
          <% if @match.winner && @match.winner == @match.home_team %>
            <span class="board-elo-up pad">+<%= @match.home_new_elo - @match.home_old_elo %></span>
          <% elsif @match.winner && @match.winner == @match.away_team %>
            <span class="board-elo-down pad"><%= @match.home_new_elo - @match.home_old_elo %></span>
          <% else %>
            <span class="board-elo-sam pad">0</span>
          <% end %>
        </td>
      </tr>
      
      <tr>
        <td>ELO Multiplier</td>
        <td colspan=2><%= @match.multiplier %></td>
      </tr>

      <tr>
        <td>Tournament Round</td>
        <td colspan=2><%= @match.tournament_round_id %></td>
      </tr>

      <tr>
        <td>Tournament Order</td>
        <td colspan=2><%= @match.tournament_order %></td>
      </tr>

      <tr>
        <td>Comment</td>
        <td colspan=2><%= @match.comment %></td>
      </tr>
    </table>
  </div>
</div>