config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'root#index'

  resources :admin, only: [:index]

  namespace :admin do
    resources 'canam' do
      delete :tournament_round_matches
      post :generate_tournament_round_matches
      get :assign_courts # need a param here
      post :process_courts
      collection do
        post :import
        get :player
        get :summary
      end
    end
    resources 'matches'
    resources 'seasons', only: [:show]
    resources 'teams' do
      collection do
        post :import
        post :import_selection
      end
    end
  end

  resources :divisions, only: [:index, :show]
  get '/divisions/:id/playoff', to: 'divisions#show_playoff', as: :division_playoff
  get '/divisions/:id/week/:week', to: 'divisions#week', as: :division_week
  post '/divisions/:id/week/:week/report', to: 'divisions#week_report', as: :division_week_report

  resources :faq, only: [:index]
  get 'bracket/current', to: 'bracket#current', as: :current_bracket
  resources :bracket
  resources :games, only: [:update]
  resources :isa, only: [:index]
  resources :live, only: [:index, :lower_third, :four_frame_summary, :four_game, :full_game, :two_game, :summary]
  get 'live/lower_third', to: 'live#lower_third', as: :lower_third
  get 'live/four_frame_summary', to: 'live#four_frame_summary', as: :four_frame_summary
  get 'live/full_game', to: 'live#full_game', as: :full_game
  get 'live/summary', to: 'live#summary', as: :summary
  get 'live/four_game', to: 'live#four_game', as: :four_game
  get 'live/two_game', to: 'live#two_game', as: :two_game
  get 'live/si/:id', to: 'live#si'
  get 'live/si', to: 'live#si'

  resources :live_events, only: [:update]
  resources :matches
  get 'matches/:id/ae_data', to: 'matches#ae_data', as: :match_ae_data
  resources :privacy, only: [:index]
  resources :root, only: [:index]
  resources :royal_palms_calendar, only: [:index]
  post 'rpc_events', to: 'royal_palms_calendar#index', as: :rpc_events
  resources :seasons, only: [:index, :show]
  get '/seasons/:id/report', to: 'seasons#report', as: :season_report
  resources :teams, only: [:index, :show]
  resources :tournament_rounds, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :season
  has_and_belongs_to_many :teams
  has_many :matches

  delegate :location, to: :season

  def match_time_for_week(week)
    day = season.start_date
    if day_of_week
      days_diff = day_of_week - 1
      day += days_diff.days
    end

    (week - 1).times do
      day += 1.week
    end

    Time.find_zone('America/New_York').parse("#{day} #{time}")
  end

  def matches_for_week(week)
    matches.where(time: match_time_for_week(week)).order(:court_id)
  end

  def report_for_week(week)
    output = "\e[36mResults (winner underlined):\e[0m\n"
    output += "#{season.name} - #{name} Division\n"
    output += match_time_for_week(week).in_time_zone('America/Chicago').to_s + "\n\n"

    matches_for_week(week).each do |m|
      output += "#{m.id}\t"
      output += "#{m.location}\t"
      output += "\e[4m" if m.away_score > m.home_score
      output += m.away_team.name + ' (A)'
      output += "\e[24m" if m.away_score > m.home_score
      output += ' vs. '
      output += "\e[4m" if m.home_score > m.away_score
      output += m.home_team.name + ' (H)'
      output += "\e[24m" if m.home_score > m.away_score
      output += "\n"
    end

    output
  end

  def sorted_teams
    return Division.frozen_id_to_team(JSON.parse(final_standings)) if final_standings

    Team.sort_by_rank(teams.map do |t|
                        {
                          team: t,
                          wins: t.league_record(self)[:wins],
                          losses: t.league_record(self)[:losses]
                        }
                      end)
  end

  def freeze!
    self.final_standings = nil
    save
    self.final_standings = JSON.pretty_generate(Division.frozen_team_to_id(sorted_teams))
    save
  end

  def la_name
    output = season.name
    output += ' ' + (day_of_week == 1 ? 'Monday' : 'Tuesday')
    output += ' (' + Time.parse(time).strftime('%-l:%M%P') + ')'
    output += ' ' + name.split.last + ' Division'
    output
  end

  def la_csv
    require 'csv'

    attributes = %w[
      SUB_PROGRAM
      HOME_TEAM
      AWAY_TEAM
      DATE
      START_TIME
      END_TIME
      LOCATION
      SUB_LOCATION
      TYPE
      NOTES
    ]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      matches.order(:time, :location).each do |m|
        row = []
        row << nil
        row << m.home_team.name
        row << m.away_team.name
        row << m.time.in_time_zone('America/New_York').strftime('%-m/%-d/%Y')
        row << m.time.in_time_zone('America/New_York').strftime('%H:%M')
        row << (m.time + 1.hour).in_time_zone('America/New_York').strftime('%H:%M')
        row << 'the royal palms shuffleboard club'
        row << m.court.name
        row << 'REGULAR_SEASON'
        row << nil
        csv << row
      end
    end
  end

  def self.frozen_id_to_team(input)
    output = []

    input.each do |t|
      output.push(
        team: Team.find(t['team_id']),
        wins: t['wins'],
        losses: t['losses']
      )
    end

    output
  end

  def self.frozen_team_to_id(input)
    output = []

    input.each do |t|
      output.push(
        team_id: t[:team].id,
        wins: t[:wins],
        losses: t[:losses]
      )
    end

    output
  end

  def next_division
    d = Division.find_by(id: id + 1)
    return d if d && season_id == d.season_id

    nil
  end

  def playoff_prediction
    output = []

    teams.each do |t|
      record = t.league_record(self)

      matches = t.matches.where(division: self, away_score: 0, home_score: 0)

      matches.each do |m|
        estimate = if m.home_team_id == t.id
                     ::Elo::Rating.new(old_rating: m.home_team.elo_cache, other_rating: m.away_team.elo_cache).send(:expected)
                   else
                     ::Elo::Rating.new(old_rating: m.away_team.elo_cache, other_rating: m.home_team.elo_cache).send(:expected)
                   end

        record[:wins] += estimate
        record[:losses] += (1 - estimate)
      end
      output.push(
        team: t,
        wins: record[:wins],
        losses: record[:losses]
      )
    end

    Team.sort_by_rank(output).map do |t|
      {
        team: t[:team],
        wins: t[:wins].round,
        losses: t[:losses].round
      }
    end
  end

  # Returns array of Matches, but doesn't save them
  def setup_matches(location = Location.find_by(name: 'Royal Palms Brooklyn'))
    output_matches = []

    # Sort teams into away and home via snake order
    s_teams = teams.order(:elo_cache)

    raise 'Automatic schedule requires 12 teams' unless teams.count == 12

    away_teams = [
      s_teams[0],
      s_teams[3],
      s_teams[4],
      s_teams[7],
      s_teams[8],
      s_teams[11]
    ]
    home_teams = [
      s_teams[1],
      s_teams[2],
      s_teams[5],
      s_teams[6],
      s_teams[9],
      s_teams[10]
    ]

    courts = [
      Court.find_by(location: location, name: 'Court 01'),
      Court.find_by(location: location, name: 'Court 03'),
      Court.find_by(location: location, name: 'Court 05'),
      Court.find_by(location: location, name: 'Court 06'),
      Court.find_by(location: location, name: 'Court 08'),
      Court.find_by(location: location, name: 'Court 10')
    ]

    # Randomize teams
    away_teams.shuffle!
    home_teams.shuffle!

    # Set up 4 weeks
    4.times do |w|
      # Set up week 1
      courts.count.times do |i|
        output_matches.push(Match.new(
                              time: match_time_for_week(w + 1),
                              division: self,
                              court: courts[i],
                              away_team: away_teams[i],
                              home_team: home_teams[i],
                              away_score: 0,
                              home_score: 0
                            ))
      end

      # Away teams increase court # (1,2,3,4,etc)
      away_teams.rotate!(-1)
      # Home teams decreate court # (2,1,10,9,etc)
      home_teams.rotate!(1)
      # In week 4, home moves twice
      home_teams.rotate!(1) if w == 2
    end

    output_matches
  end

  # CSV of the weeks matchups
  def matchup_csv(week)
    require 'csv'

    CSV.generate(headers: true) do |csv|
      csv << ["#{season.name} - #{name}"]
      csv << ["Week #{week}"]

      # Leave space at top
      4.times { csv << [] }

      matches_for_week(week).each do |m|
        m.matchup_summary.each { |r| csv << r }

        # Leave room for manual info
        3.times { csv << [] }
      end
    end
  end

  def league_apps_schedule_uri
    return nil if league_apps_site_id.nil?
    return nil if league_apps_program_id.nil?

    "https://public.leagueapps.io/v1/sites/#{league_apps_site_id}/programs/#{league_apps_program_id}/schedule"
  end

  def league_apps_matches
    raise 'league_apps_site_id and league_apps_program_id required' if league_apps_schedule_uri.nil?

    res = Faraday.get(league_apps_schedule_uri) do |req|
      req.headers['la-api-key'] = ENV['LEAGUEAPPS_API_KEY']
    end

    raise "Failed to connect to League Apps - #{res.body}" if res.status >= 400

    JSON.parse(res.body)['games']
  end

  def league_apps_teams_uri
    return nil if league_apps_site_id.nil?
    return nil if league_apps_program_id.nil?

    "https://public.leagueapps.io/v1/sites/#{league_apps_site_id}/programs/#{league_apps_program_id}/teams"
  end

  def league_apps_teams
    raise 'league_apps_site_id and league_apps_program_id required' if league_apps_schedule_uri.nil?

    res = Faraday.get(league_apps_teams_uri) do |req|
      req.headers['la-api-key'] = ENV['LEAGUEAPPS_API_KEY']
    end

    raise "Failed to connect to League Apps - #{res.body}" if res.status >= 400

    JSON.parse(res.body)
  end

  def import_league_apps_matches
    league_apps_matches.each do |m|
      # Skip if already imported
      next if Match.find_by(league_apps_game_id: m['gameId'])

      # Skip if both teams are TBD
      next if m['team1'] == 'TBD' && m['team2'] == 'TBD'

      away_team = Team.find_or_create_by(location: location, param_name: Team.param_name(m['team1'])) do |t|
        t.name = m['team1']
        t.captain = m['team1Id']
      end

      away_team.divisions << self unless teams.include?(away_team)

      home_team = Team.find_or_create_by(location: location, param_name: Team.param_name(m['team2'])) do |t|
        t.name = m['team2']
        t.captain = m['team2Id']
      end

      home_team.divisions << self unless teams.include?(home_team)

      court_name = "Court #{('%02d' % m['subLocationName'].split(/ /)[1].to_i)}"
      court = location.courts.find_by(name: court_name)

      raise 'Could not find court' unless court

      time = Time.at(m['startTime'] / 1000)

      Match.create!(
        away_team: away_team,
        home_team: home_team,
        away_score: m['team1Score'] || 0,
        home_score: m['team2Score'] || 0,
        division: self,
        time: time,
        court: court,
        league_apps_game_id: m['gameId']
      )
    end
  end

  def import_league_apps_teams
    league_apps_teams.each do |la_t|
      next if la_t['teamName'] == 'TBD'

      new_team = Team.find_or_create_by(location: location, param_name: Team.param_name(la_t['teamName'])) do |t|
        t.name = la_t['teamName']
        t.captain = la_t['teamId']
      end

      new_team.divisions << self unless teams.include?(new_team)
    end
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def index
    @divisions = Division.all.order('season_id DESC', :day_of_week, :time)
  end

  def show
    @division = Division.find(params[:id])

    @teams = @division.sorted_teams
    @show_elo = @division.season.latest?
    @show_elo_change = @division.season.latest? && @division.season.started?

    respond_to do |format|
      format.html
      format.csv { send_data @division.la_csv, filename: "league-schedule-#{@division.name.parameterize}.csv" }
    end
  end

  def show_playoff
    @division = Division.find(params[:id])

    if @division.final_standings
      flash[:alert] = 'Rankings are final, no prediction needed'
      redirect_to division_path(params[:id]) and return
    end

    @teams = @division.playoff_prediction
    @show_elo = true
    @show_elo_change = false

    respond_to do |format|
      format.html { render template: 'divisions/show' }
    end
  end

  def week
    admin? if params[:report]

    @division = Division.find(params[:id])

    @week = params[:week].to_i
    raise ActionController::RoutingError, 'Only Weeks 1-8 are valid' unless Array(1..8).include?(@week)

    @matches = @division.matches_for_week(@week)
    @time = @division.match_time_for_week(@week)

    respond_to do |format|
      format.html
      format.csv { send_data @division.matchup_csv(@week), filename: "matchup-#{@division.name.parameterize}-week#{@week}.csv" }
    end
  end

  def week_report
    admin?

    division = Division.find(params[:id])
    week = params[:week].to_i

    params.each do |param, value|
      next unless param.starts_with?('Court ')

      # TODO: fix this to work for multiple locations
      l = Location.find_by(name: 'Royal Palms Chicago')
      c = Court.find_by(name: param, location: l)
      m = Match.find_by(court: c, division: division, time: division.match_time_for_week(week))

      m.update(home_score: 1, away_score: 0) if value == 'home'
      m.update(home_score: 0, away_score: 1) if value == 'away'

      m.calculate_elo
    end

    flash[:success] = 'Results Saved!'

    redirect_to(division_week_path(division.next_division, week, report: true)) and return if division.next_division

    redirect_to root_path
  end

  def admin?
    return if current_user && current_user.is_admin?

    flash[:error] = 'You are not authorized to view that page'
    redirect_to root_path
  end
end

app/views/divisions/_division_rank.html.erb
<div class="board-table">
  <div class="row board-title-row">
    <% if division %>
      <div class="col-7">
        <div class="dummy-7"></div>
        <div class="in board">
          <%= title %>
        </div>
      </div>

      <div class="col-2">
        <div class="dummy-2"></div>
        <div class="in board">
          Record
        </div>
      </div>

    <% else %>

      <div class="col-9">
        <div class="dummy-9"></div>
        <div class="in board">
          <%= title %>
        </div>
      </div>

    <% end %>

    <div class="col-3">
      <div class="dummy-3"></div>
      <div class="in board">
        ELO
      </div>
    </div>

  </div>

  <% teams.each_with_index do |t, i| %>
    <div class="row board-row">

      <div class="col-1">
        <div class="dummy"></div>
        <div class="in board board-rank">
          <%= i + 1 %>
        </div>
      </div>

      <% if division %>
        <div class="col-6">
          <div class="dummy-6"></div>
          <div class="in board board-name">
            <%= t.name %>
          </div>
        </div>

        <div class="col-1">
          <div class="dummy"></div>
          <div class="in board board-wins">
            <%= t.league_record(division)[:wins] %>
          </div>
        </div>

        <div class="col-1">
          <div class="dummy"></div>
          <div class="in board board-losses">
            <%= t.league_record(division)[:losses] %>
          </div>
        </div>

      <% else %>

        <div class="col-8">
          <div class="dummy-8"></div>
          <div class="in board board-name">
            <%= t.name %>
          </div>
        </div>

      <% end %>

      <div class="col-2">
        <div class="dummy-2"></div>
        <div class="in board board-elo">
          <%= t.elo_cache %>
        </div>
      </div>

      <div class="col-1">
        <div class="dummy"></div>
        <% if t.elo_cache > t.previous_elo %>
          <div class="in board board-elo-up">+<%= t.elo_cache - t.previous_elo %></div>
        <% elsif t.elo_cache < t.previous_elo %>
          <div class="in board board-elo-down">-<%= t.previous_elo - t.elo_cache %></div>
        <% else %>
          <div class="in board board-elo-same">0</div>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

app/views/divisions/current_season.html.erb
<div class="row">
  <% @monday.each do |d| %>
    <div class="col-md-4">
      <%= render partial: 'divisions/division_rank', locals: { division: d } %>
    </div>
  <% end %>
</div>

<div class="row">
  <% @tuesday.each do |d| %>
    <div class="col-md-4">
      <%= render partial: 'divisions/division_rank', locals: { division: d } %>
    </div>
  <% end %>
</div>

app/views/divisions/index.html.erb
<% provide :title, 'Divisions' %>
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table class="table">
      <tr>
        <td>Season</td>
        <td>Division</td>
        <td></td>
        <td></td>
      </tr>

      <% @divisions.each do |d| %>
        <tr>
          <td><%= d.season.name %></td>
          <td><%= d.name %></td>
          <td><%= link_to 'Rankings', division_path(d.id) %></td>
          <td><%= link_to 'Schedule', division_week_path(d.id, 1) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/divisions/show.html.erb
<% provide :title, "#{@division.season.name} - #{@division.name}" %>
<h3><%= @division.season.name %> - <%= @division.name %></h3>

<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <span class="week-link"><%= link_to "Schedule", division_week_path(params[:id], 1) %></span>

    <%= render partial: 'layouts/rank_board', locals: {
      title: "#{@division.name} Division",
      teams: @teams,
      rank_widths: rank_board_width(true, true, @show_elo, @show_elo_change)
    } %>
  </div>
</div>

app/views/divisions/week.html.erb
<% provide :title, "Week #{ @week }, #{ @division.name } Division" %>

<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <div class="row">
      <div class="col-12">
        <div class="week-arrows float-right d-print-none">
          <% if current_user && current_user.is_admin? && !params[:report] %>
            <%= link_to "Report Results", division_week_path(params[:id], @week, report: true) %> |
          <% end %>
          <%= link_to "Rankings", division_path(params[:id]) %> |
          <% if @week > 1 %>
            <%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe, division_week_path(params[:id], @week - 1) %>
          <% else %>
            <i class="fas fa-arrow-left"></i>
          <% end %>
          <% if @week < 8 %>
            <%= link_to '<i class="fas fa-arrow-right"></i>'.html_safe, division_week_path(params[:id], @week + 1) %>
          <% else %>
            <i class="fas fa-arrow-right"></i>
          <% end %>
        </div>
        <div class="week-details float-left">
          <%= "Week #{ @week } - #{ @division.name } Division - #{ @division.season.name }" %><br />
          <%= @time.in_time_zone('America/Chicago').strftime("%A, %B #{ @time.in_time_zone('America/Chicago').day.ordinalize } %Y, %-l:%M%P") %><br />
        </div>
      </div>
    </div>

    <br />

    <div class="row">
      <table class="table">
        <%= form_tag(division_week_report_path, method: 'post') do %>
          <thead>
            <tr>
              <td>Location</td>
              <td>Away Team</td>
              <% if params[:report] %><td>Win</td><% end %>
              <td>Home Team</td>
            </tr>
          </thead>
          <tbody>
            <% @matches.each do |m| %>
              <tr>
                <td><%= m.court.name %></td>
                <td class="<%= 'font-weight-bold' if m.away_score > m.home_score %>">
                  <span class="d-print-none">
                    <span data-toggle="tooltip" data-placement="top" title="Current ELO: <%= m.away_team.elo_cache %>">
                      <%= link_to m.away_team.display_name, team_path(m.away_team) %>
                    </span>
                  </span>
                  <span class="d-none d-print-block">
                    <%= m.away_team.display_name %>
                  </span>
                </td>

                <% if params[:report] %>
                  <td>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input position-static" type="radio" name="<%= m.court.name %>" value="away">
                      <input class="form-check-input position-static" type="radio" name="<%= m.court.name %>" value="home">
                    </div>
                  </td>
                <% end %>

                <td class="<%= 'font-weight-bold' if m.home_score > m.away_score %>">
                  <span class="d-print-none">
                    <span data-toggle="tooltip" data-placement="top" title="Current ELO: <%= m.home_team.elo_cache %>">
                      <%= link_to m.home_team.display_name, team_path(m.home_team) %>
                    </span>
                  </span>
                  <span class="d-none d-print-block">
                    <%= m.home_team.display_name %>
                  </span>
                </td>
              </tr>
            <% end %>
            <% if params[:report] %>
              <tr>
                <td colspan="4">
                  <%= submit_tag "Submit", class: 'btn btn-info' %>
                  <%= link_to "Cancel", division_week_path(params[:id], @week), { role: 'button', class: 'btn btn-outline-secondary' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>